using Microsoft.EntityFrameworkCore.Migrations;

namespace desafio_mvc.Migrations
{
    public partial class PopulaReceitas : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("INSERT INTO Receitas(Nome, TempoDePreparo, ImagemUrl, ModoDePreparo, NomeDoAutor, Rendimento, Dificuldade, IsPreferido, Status, CategoriaId) VALUES ('Granola caseira',60,'granola.jpg','1 - Em uma vasilha, coloque todos os ingredientes e misture bem. 2 - Transfira para uma forma de alumínio, espalhe e asse em forno preaquecido a 180° graus por 50 minutos. 3 - Lembre-se de mexer a cada 10 minutos para não perder o ponto. 4 - Estará pronto quando estiver bem cheirosa e crocante. Agora é só aproveitar.','Raphael Azevedo',1,0,0,1,1)");
            migrationBuilder.Sql("INSERT INTO Receitas(Nome, TempoDePreparo, ImagemUrl, ModoDePreparo, NomeDoAutor, Rendimento, Dificuldade, IsPreferido, Status, CategoriaId) VALUES ('Pão de abóbora com polvilho',30,'polvilho.PNG','1 - Em um processador, adicione o purê de abóbora, o polvilho, o azeite, a chia, o sal e bata até misturar bem (você pode fazer na mão, também). 2 - Caso fique muito seco, acrescente a água. 3 - Transfira para um prato, pegue pequenas porções da massa, molde em formato de bolinhas e disponha em uma forma untada. Leve ao forno preaquecido a 200 ºC por cerca de 30 minutos. 5 - Agora é só servir. Bom apetite.','Raphael Azevedo',2,0,1,1,2)");
            migrationBuilder.Sql("INSERT INTO Receitas(Nome, TempoDePreparo, ImagemUrl, ModoDePreparo, NomeDoAutor, Rendimento, Dificuldade, IsPreferido, Status, CategoriaId) VALUES ('Panqueca fit com whey de cacau',20,'panqueca.PNG','1 - Em um recipiente, amasse bem as bananas. 2 - Adicione os ovos, a farinha, o whey, as sementes e misture até incorporar. 3 - Unte uma frigideira com um pouco de azeite, esquente e despeje uma quantidade da massa. 4 - Deixe assar bem e depois vire para dourar o outro lado. 5 - Repita o processo até a massa acabar. 6 - Decore com a noz-pecan, as frutas vermelhas e o mel. 7 - Agora é só servir. Bom apetite.','Raphael Azevedo',4,0,1,1,1)");
            migrationBuilder.Sql("INSERT INTO Receitas(Nome, TempoDePreparo, ImagemUrl, ModoDePreparo, NomeDoAutor, Rendimento, Dificuldade, IsPreferido, Status, CategoriaId) VALUES ('Bolo de amêndoas low carb',45,'bolo.jpg','1 - Em um recipiente, adicione todos os ingrediente e misture bem até formar uma massa. 2 - Despeje a massa em uma forma untada e leve ao forno preaquecido a 180 ºC por cerca de 40 minutos. 3 - Agora é só servir. Bom apetite.','Raphael Azevedo',1,0,1,1,1)");
            migrationBuilder.Sql("INSERT INTO Receitas(Nome, TempoDePreparo, ImagemUrl, ModoDePreparo, NomeDoAutor, Rendimento, Dificuldade, IsPreferido, Status, CategoriaId) VALUES ('Omelete de forno fácil',40,'omelete.PNG','1 - Coloque todos os ingredientes em uma vasilha e misture muito bem. 2 - Depois de tudo misturado, despeje em uma forma untada e enfarinhada e leve ao forno em temperatura de 180° graus por mais ou menos uns 30 minutos ou até que a omelete esteja completamente assada.','Raphael Azevedo',6,2,1,1,2)");
            migrationBuilder.Sql("INSERT INTO Receitas(Nome, TempoDePreparo, ImagemUrl, ModoDePreparo, NomeDoAutor, Rendimento, Dificuldade, IsPreferido, Status, CategoriaId) VALUES ('Omelete de forno com queijo e tomate',30,'omelete2.PNG','1 - Reúna todos os ingredientes; 2 - Coloque os ovos, o leite, o sal, a pimenta e o azeite em uma tigela e misture até homogeneizar; 3 - Em um refratário (ou forma) pequeno e untado, coloque o tomate, o queijo picado em cubinhos, o manjericão, o cream cheese e a mistura de ovos; 4 - Salpique a salsinha por cima e asse o omelete em forno pré-aquecido a 200º graus por cerca de 20 minutos ou até ficar dourado; 5 - Agora é só servir. Bom apetite!','Raphael Azevedo',6,2,1,1,2)");
            migrationBuilder.Sql("INSERT INTO Receitas(Nome, TempoDePreparo, ImagemUrl, ModoDePreparo, NomeDoAutor, Rendimento, Dificuldade, IsPreferido, Status, CategoriaId) VALUES ('Dadinhos de tapioca',240,'dadinhos.PNG','1 - Prepare uma forma de 20 x 25 cm forrada com filme plástico 2 - Rale o queijo no ralo grosso e coloque-o em uma vasilha 3 - Adicione a tapioca, coloque uma pitada de sal, um pouquinho de pimenta, orégano e misture 4 - Adicione o leite fervente e vá mexendo até incorporar o leite e a massa ficar homogênea 5 - Espalhe a mistura na forma preparada, alise para ficar retinha e leve para a geladeira por no mínimo 3 horas 6 - Após esse tempo, tire da geladeira, corte em quadradinhos e acomode os cubinhos em uma assadeira antiaderente ou forrada com papel manteiga 7 - Leve para assar por uns 40 minutos, até que fiquem douradinhos (se preferir, você pode fazer frito) 8 - Retire do forno 9 - Está pronto!','Raphael Azevedo',4,2,1,1,2)");
            migrationBuilder.Sql("INSERT INTO Receitas(Nome, TempoDePreparo, ImagemUrl, ModoDePreparo, NomeDoAutor, Rendimento, Dificuldade, IsPreferido, Status, CategoriaId) VALUES ('Crepioca de queijo com tomate e orégano',10,'crepioca.PNG','1 - Misture o ovo, a tapioca e o sal. 2 - Coloque o azeite na frigideira e aqueça 3 - Despeje a massa da crepioca. 4 - Espere soltar do fundo da frigideira e vire. 5 - Adicione o queijo, o tomate o orégano. 6 - Tampe a frigideira e espere de 1 a 2 minutos. 7 - Sirva aberto ou enrolado e cortado em 3 partes. Bom apetite.','Raphael Azevedo',1,0,2,1,2)");

        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("Delete from Receitas");
        }
    }
}
